export type Db = string[][];

export const db: Db = [
  [
    "Santa's Unicorn Llama",
    "Jingle Bell Elephant",
    "Candy Cane Sloth",
    "Reindeer-O-Matic",
    "Frosty the Hedgehog",
    "Turbo Sleigh Flamingo",
    "Invisible Snow Panda",
    "Twinkle-Light Octopus",
    "Gingerbread Shark",
    "Nutcracker Parrot",
    "Snow Cloud Kangaroo",
    "Icicle Koala",
    "Hot Cocoa Squirrel",
    "Velcro Elf Penguin",
    "Starlight Corgi",
    "Glow-in-the-Dark Reindeer Owl",
    "Sleigh T-Rex on Wheels",
    "Marshmallow Hot Cocoa Catfish",
    "Peppermint Zebra",
    "Snowcone Narwhal",
    "Tinsel Snail",
    "Sugarplum Alpaca",
    "Caffeinated Christmas Platypus",
    "Mistletoe Crocodile",
    "Pepperoni Pizza Elf Dragon",
    "Confetti Snow Porcupine",
    "Bubblegum Ornament Spider",
    "Laser-Tag North Pole Fox",
  ],
  [],
];
